[package]
name = "mpktool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
binrw = "0.14.1"
clap = { version = "4.5.27", features = ["derive"] }
hex = "0.4.3"
rand = "0.8.5"
unfmt = "0.2.2"
